name: tripswipe
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  cloud_firestore: ^4.13.6
  cool_alert: ^2.0.1
  cupertino_icons: ^1.0.2
  file_picker: ^6.1.1
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  firebase_storage: ^11.5.6
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  flutter_phone_direct_caller: ^2.1.1
  flutter_rating_bar: ^4.0.1
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  hexcolor: ^3.0.1
  image_picker: ^1.0.4
  intl_phone_number_field: ^0.1.8
  provider: ^6.1.1
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - img/Login page.png
    - img/Login page (1).png
    - img/Group (5).png
    - img/login-concept-illustration_114360-757__1_-removebg-preview.png
    - img/login-concept-illustration_114360-757 (1).jpg
    - img/signup.jpg
    - img/signup-removebg-preview.png
    - img/cab_booking-removebg-preview.png
    - img/car_rentservieses-removebg-preview.png
    - img/car-repair-maintenance--removebg-preview.png
    - img/Group (6).png
    - img/isometric-auto-repair-horizontal-background-with-text-indoor-garage-composition-with-two-workers-repairing-car_1284-60836-removebg-preview.png
    - img/accssoriesin_car-removebg-preview.png
    - img/acceesssorrrieees-removebg-preview.png
    - img/car-interior-dark_1284-5362-removebg-preview.png
    - img/accsss-removebg-preview.png
    - img/mainebackground.png
    - img/profile.jpeg
    - img/carmain.jpg
    - img/carmain-removebg-preview.png
    - img/Untitled-design-85-e1628428158861.png
    - img/car red main.jpg
    - img/car_red_main-removebg-preview.png
    - img/autorickshw-removebg-preview.png
    - img/TEMPO-TRAVELLER-ON-RENT-IN-PUNE-removebg-preview.png
    - img/hatchbacj 2.png
    - img/sedan 1.png
    - img/suv1 1.png
    - img/maninbottomimage-removebg-preview.png
    - img/turist1.png
    - img/buspurepng.com-white-busbusvehiclecarrying-passengerslarge-motor-vehiclecoachminibus-1701528460754rm19f
      1.png
    - img/hatchback-removebg-preview.png
    - img/sedan-removebg-preview.png
    - img/suv-removebg-preview.png
    - img/carrent-removebg-preview.png
    - img/bike-removebg-preview.png
    - img/wheel-vector-125901-removebg-preview.png
    - img/carwheels-removebg-preview.png
    - img/idea-removebg-preview.png
    - img/workshopp-removebg-preview.png
    - img/helm-2060063_960_720.png
    - img/idea.jpg
    - img/acs-removebg-preview.png
    - img/idea.jpg
    - img/pro.png
    - img/pro.png
    - img/Edit cab.png
    - img/cabbooking2myser-removebg-preview.png
    - img/carrentelservies-removebg-preview.png
    - img/userbackmain.png
    - img/rentuserpage-removebg-preview.png
    - img/carride-removebg-preview.png
    - img/bikeride-removebg-preview.png
    - img/usercabbooking-removebg-preview.png
    - img/selectlocation-removebg-preview.png
    - img/cabbookimg-removebg-preview.png
    - img/usercabbooking-removebg-preview.png
    - img/usercabbooking-removebg-preview.png
    - img/userbackmain-removebg-preview (1).png
    - img/itslucky.png
    - img/newcab1.jpg
    - img/selectyourlocationcb1-removebg-preview.png
    - img/locateaarow.png
    - img/locatearwrownded.png
    - img/redrowndwerd.png
    - img/chooseyoureride-removebg-preview.png
    - img/chooseyourride-removebg-preview.png
    - img/selecloc-removebg-preview.png
    - img/autorikshaw-removebg-preview.png
    - img/travaller-removebg-preview.png
    - img/carslect-removebg-preview.png
    - img/primehatchbackx-removebg-preview.png
    - img/primesedan-removebg-preview.png
    - img/primsuv-removebg-preview.png
    - img/travaller-removebg-preview (1).png
    - img/busaahn-removebg-preview.png
    - img/tempotrav_prev_ui.png
    - img/starbitaxidriver.jpg
    - img/taxid3.jpg
    - img/tacid2.jpg
    - img/enjoyyourride_prev_ui.png
    - img/carrentmain_aahnn-removebg-preview.png
    - img/rentpageimagemain-removebg-preview.png
    - img/carrentmain_aahnn-removebg-preview.png
    - img/caristhe.png
    - img/red-sports-car-isolated-white-vector_53876-67349-removebg-preview.png
    - img/motorscycle-removebg-preview.png
    - img/zacces.png
    - img/zswift-removebg-preview.png
    - img/zswift-removebg-preview.png
    - img/maruti-alto-800-1000x1000-removebg-preview.png
    - img/baleano-removebg-preview.png
    - img/hero-x-plus-small-removebg-preview.png
    - img/honda-cb-unicorn-160-disc-bike-removebg-preview.png
    - img/royal-enfield-himalayan-bikes-removebg-preview.png
    - img/access-125-10.png
    - img/YELLOW-COCKTAIL-STD.png
    - img/honda-activa-6g-1671442494-6679805-removebg-preview.png
    - img/location_prev_ui.png
    - img/carworkshopmaine.jpg
    - img/caracs1-removebg-preview.png
    - img/caracs4.jpg
    - img/caracs3.jpg
    - img/caracs2.jpg
    - img/Rating.png
    - img/otpiaahn.png
    - img/Rating (1).png
    - img/enjoy_ride-removebg-preview.png
    - img/slazzer-edit-image.png
    - img/slazzer-edit-image_prev_ui.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
