// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgRl4v8lD3fZBf4F9mZzcEIT8cXmd3vXg',
    appId: '1:658816945423:web:9738bde1f28e504725c27a',
    messagingSenderId: '658816945423',
    projectId: 'tripswipe-35865',
    authDomain: 'tripswipe-35865.firebaseapp.com',
    storageBucket: 'tripswipe-35865.appspot.com',
    measurementId: 'G-XM7ZVHC4Q8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe29vBB6XUL7ApS5JOMbrp7eulSgdxuSs',
    appId: '1:658816945423:android:8d5a36864c6dfec925c27a',
    messagingSenderId: '658816945423',
    projectId: 'tripswipe-35865',
    storageBucket: 'tripswipe-35865.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGMUsKE7onC_qoxagipPPOmsfAFyy4mnY',
    appId: '1:658816945423:ios:f62e74fbb16f0f7225c27a',
    messagingSenderId: '658816945423',
    projectId: 'tripswipe-35865',
    storageBucket: 'tripswipe-35865.appspot.com',
    iosBundleId: 'com.example.tripswipe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGMUsKE7onC_qoxagipPPOmsfAFyy4mnY',
    appId: '1:658816945423:ios:c883db16ac3c777725c27a',
    messagingSenderId: '658816945423',
    projectId: 'tripswipe-35865',
    storageBucket: 'tripswipe-35865.appspot.com',
    iosBundleId: 'com.example.tripswipe.RunnerTests',
  );
}
